#!/usr/bin/env bash
# create-release.sh - helper to create a GitHub release using the GH CLI
# Usage: ./scripts/operational/create-release.sh <tag> [--draft]

set -euo pipefail

TAG="$1"
DRAFT_FLAG=""
if [ "${2:-}" = "--draft" ]; then
  DRAFT_FLAG="--draft"
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh CLI not found. Install from https://cli.github.com/"
  exit 1
fi

if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "ERROR: GITHUB_TOKEN not set. Export a token with repo scope to create releases."
  exit 1
fi

# Read changelog-like message from last commit and format it
COMMIT_MSG=$(git log -1 --pretty=%B || true)
CLEAN_MSG=$(echo "$COMMIT_MSG" | sed -E 's/^(feat|fix|perf|refactor|docs|chore|ci|test):\s*//')

RELEASE_TITLE="$TAG"
RELEASE_BODY="${CLEAN_MSG}\n\n- Generated by scripts/operational/create-release.sh"

echo "Creating GitHub release: $TAG"

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "ERROR: Release $TAG already exists"
  exit 1
fi

# Use GH CLI to create the release
if gh release create "$TAG" --title "$RELEASE_TITLE" --notes "$RELEASE_BODY" $DRAFT_FLAG; then
  echo "[OK] Release $TAG created"
else
  echo "[ERROR] Failed to create release $TAG"
  exit 1
fi

exit 0
